FROM node:18.16.1

WORKDIR /srv

COPY . .

RUN npm install
RUN npm install pm2 -g
ENV NODE_ENV=develop
#CMD [ "pm2-runtime", "start" , "./bin/www"]
ENTRYPOINT ["sh", "-c", "pm2 start pm2.config.json --no-daemon"]
EXPOSE 3000